title: "HR Questions Guide"
description: "A collection of common HR interview questions with sample answers, divided into non-technical and technical categories."
author: "John"
theme: jekyll-theme-cayman

header_pages:
  - title: "Home"
    url: "/"
  - title: "Non-Technical Questions"
    url: "/non_technical_questions.md"
  - title: "Technical Questions"
    url: "/technical_questions.md"
