title: "HR Questions Guide"
description: "A collection of common HR interview questions with sample answers."
author: "John"
theme: minimal-mistakes-jekyll
markdown: kramdown

header_pages:
  - title: "Home"
    url: "/"
  - title: "Non-Technical Questions"
    url: "/non_technical_questions/"
  - title: "Technical Questions"
    url: "/technical_questions/"

social_links:
  github: "https://github.com/hongzz0618"
  linkedin: "https://www.linkedin.com/in/hongzz"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
